### ISSUE TITLE
handle 500 strand

### ISSUE THREAD

**Issue by fishkingsin** [Sh4d/LPD8806#3]
Hi 
first of all thank for your library , I am happy with playing around the LED Strip

however I got 500 strand need to handle
it seems getting slow when the length of the LPD8806 longer than 300 strand
any hints to improve the performance?
thanks

**Comment by adammhaile** [comment]
Unfortunately this is just a limitation of the platform you are using.
The problem is two-fold. First, you are using python, which is interpreted
and you take a performance hit because of this. Second, the default setup
for SPI on the raspberry pi is not running at full speed so you cannot get
max performance out of it. The latter is likely the biggest problem here.
 But basically you are just going to see slower updates the more lights you
use.
